[breaking] refactor worktree

diff --git a/patches/patch b/patches/patch
--- a/patches/patch
+++ b/patches/patch
@@ -2,6 +2,11 @@
 
 source ../utils.sh
 
+__dry_run=false
+if [ $1 == "--dry" ]; then
+    __dry_run=true
+fi
+
 for patch in $(find ./*/ -type f) ; do
     if [[ "$(basename "$patch")" == .* ]] ; then
         log::wrn "Skip: $patch"
@@ -12,14 +17,19 @@ for patch in $(find ./*/ -type f) ; do
     if [[ $patch == *.patch ]] ; then
         target_file="${target_file%.patch}"
         log::msg "Patch: $target_file"
-        if ! sudo patch -N -s --reject-file=- "$target_file" < "$patch" ; then
-            log::err "Patch failed: $target_file"
+        if ! $__dry_run ; then
+            if ! sudo patch -N -s --reject-file=- "$target_file" < "$patch" ; then
+                log::err "Patch failed: $target_file"
+            fi
         fi
     else
         log::msg "Swap:  $target_file"
-        if ! sudo cp --no-preserve=mode,ownership -rf "$patch" "$target_file" ; then
-            log::err "Swap failed: $patch"
+        if ! $__dry_run ; then
+            if ! sudo cp --no-preserve=mode,ownership -rf "$patch" "$target_file" ; then
+                log::err "Swap failed: $patch"
+            fi
         fi
     fi
 done
 
+unset __dry_run
diff --git a/systemd/setup_services b/systemd/setup_services
--- a/systemd/setup_services
+++ b/systemd/setup_services
@@ -8,22 +8,33 @@ if [ -z "$SETUP_USER" ]; then
     cd .. && source utils.sh && cd "$curr_dir"
 fi
 
+__dry_run=false
+if [ $1 == "--dry" ]; then
+    __dry_run=true
+fi
+
 if [ ! -d /usr/sbin/dotfiles ]; then
     log::msg "linking sbin to /usr/sbin"
-    sudo ln -s "$(pwd)/sbin/" /usr/sbin/dotfiles
+    if ! $__dry_run ; then
+        sudo ln -s "$(pwd)/sbin/" /usr/sbin/dotfiles
+    fi
 fi
 
 for service in $(read_list "./enabled-system-services.txt"); do
     log::msg "enabling system service: $service"
-    if ! sudo systemctl enable --now "$service"; then
-        log::err "failed to setup: $service"
+    if ! $__dry_run ; then
+        if ! sudo systemctl enable --now "$service"; then
+            log::err "failed to setup: $service"
+        fi
     fi
 done
 
 for service in $(read_list "./enabled-user-services.txt"); do
     log::msg "enabling user service: $service"
-    if ! sudo systemctl --user -M "$SETUP_USER"@ enable --now "$service"; then
-        log::err "failed to setup: $service"
+    if ! $__dry_run ; then
+        if ! sudo systemctl --user -M "$SETUP_USER"@ enable --now "$service"; then
+            log::err "failed to setup: $service"
+        fi
     fi
 done
 
