[shlib] use lib instead of util functions

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -8,10 +8,13 @@ if [ -z "$GIT_DIR" ]; then
     echo "Not in dotfiles directory. Exiting ..."
     exit 1
 fi
-if [ ! -d "install" ]; then
-    echo "install/ directory is not present. Exiting ..."
-    exit 1
-fi
+required_dirs=("include" "install")
+for dir in "${required_dirs[@]}"; do
+    if [ ! -d "$dir" ]; then
+        echo "$dir/ directory is not present. Exiting ..."
+        exit 1
+    fi
+done
 
 # Load utils
 source "utils.sh"
@@ -53,7 +56,7 @@ SHORT_OPTS=v,s,u:,h,l
 LONG_OPTS=user:,username:,dotfiles,link,stow,packages,install,dotfiles,patch,patches,services,all,complete,help,strict,debug,verbose,remote,git,log
 OPTS=$(getopt --alternative --name 'argument error' --options $SHORT_OPTS --longoptions $LONG_OPTS -- "$@") 
 if [ $? -ne 0 ]; then
-    fat "failed to parse provided arguments"
+    std::fat "failed to parse provided arguments"
 fi
 eval set -- $OPTS
 
@@ -85,24 +88,25 @@ do
             ;;
         --remote | --git)
             if git remote set-url origin $GIT_REMOTE ; then
-                suc "Successfully updated remote: $GIT_REMOTE"
+                fmt::suc "Successfully updated remote: $GIT_REMOTE"
                 exit 0
             else 
+                fmt::err "Failed to update remote"
                 exit $?
             fi
             ;;
         -l | --log)
             logfile="setup-$(date +%s).log"
-            msg "logging output to: $logfile"
+            fmt::msg "logging output to: $logfile"
             exec 1> >(tee -a $logfile)
             exec 2>&1
             ;;
         -v | --verbose | --debug)
-            msg "debug mode enabled"
+            fmt::msg "debug mode enabled"
             set -x; 
             ;;
         -s | --strict)
-            msg "strict mode enabled"
+            fmt::msg "strict mode enabled"
             set -e; 
             ;;
         -u | --user | --username)
@@ -118,7 +122,7 @@ do
             break
             ;;
         *)
-            err "unknown option: $1"
+            fmt::err "unknown option: $1"
             usage
             ;;
     esac
@@ -128,25 +132,25 @@ done
 # Check if install arg exists
 if $SETUP_PACKAGES ; then
     if [ $# -eq 0 ]; then
-        fat "missing install list(s) or entries to install"
+        std::fat "missing install list(s) or entries to install"
     fi
 fi
 
 # Check if running as root if setting up packages or patches
 if $SETUP_PACKAGES || $SETUP_PATCHES; then 
     if [ "$EUID" -ne 0 ]; then 
-        fat "installing/patching requires root access"
+        std::fat "installing/patching requires root access"
     fi
 fi
 
 # Check username
 if [ -z "$SETUP_USER" ]; then
-    fat "cannot automatically detect user name - please provide one using the --username option"
+    std::fat "cannot automatically detect user name - please provide one using the --username option"
 fi
 
 # Check home dir
 if [ ! -d "$SETUP_HOME_DIR" ]; then
-    fat "invalid home directory: $SETUP_HOME_DIR"
+    std::fat "invalid home directory: $SETUP_HOME_DIR"
 fi
 
 if ! $SETUP_OVERRIDE ; then 
@@ -156,9 +160,9 @@ if ! $SETUP_OVERRIDE ; then
     SETUP_SERVICES=false
 fi
 
-msg "user: $SETUP_USER"
-msg "home dir: $SETUP_HOME_DIR"
-msg "install list: $*"
+fmt::msg "user: $SETUP_USER"
+fmt::msg "home dir: $SETUP_HOME_DIR"
+fmt::msg "install list: $*"
 
 export SETUP_USER
 export SETUP_HOME_DIR
@@ -173,10 +177,10 @@ if $SETUP_PACKAGES ; then
 
     # Identify package manager
     PM=$(pm_cmd)
-    msg "Package manager installation command identified as: $PM"
+    fmt::msg "Package manager installation command identified as: $PM"
 
     # Install packages
-    suc "Checks completed successfully, starting installations ..."
+    fmt::suc "Checks completed successfully, starting installations ..."
 
     function process_list ()
     {
@@ -187,27 +191,27 @@ if $SETUP_PACKAGES ; then
             if [[ "$entry" == "+"* ]]; then
                 cd "$DOTFILES_ROOT_DIR"
                 to_include=${entry#"+"}
-                msg "Importing setup script: $to_include"
+                fmt::msg "Importing setup script: $to_include"
                 process_list $(read_list "lists/$to_include")
             elif [[ "$entry" == "!"* ]]; then
                 to_post_install=${entry#"!"}
-                msg "Post-link install for : $to_post_install"
+                fmt::msg "Post-link install for : $to_post_install"
                 packages_requiring_linked_dotfiles+=(${to_post_install})
             elif [ -f "$SETUP_SCRIPT" ]; then
-                msg "Setting up via script : $entry"
+                fmt::msg "Setting up via script : $entry"
                 source ./"$SETUP_SCRIPT" "$PM"
             elif [[ "$entry" == "$AUR_PREFIX"* ]]; then
                 pkg=${entry#"$AUR_PREFIX"}
-                msg "Installing from AUR   : $pkg"
+                fmt::msg "Installing from AUR   : $pkg"
                 if inst_aur "$pkg"; then
-                    suc "Successfully installed: $pkg"
+                    fmt::suc "Successfully installed: $pkg"
                 else
                     errored_entries+=(${entry})
                 fi
             else
-                msg "Installing package    : $entry"
+                fmt::msg "Installing package    : $entry"
                 if inst "$PM" "$entry"; then
-                    suc "Successfully installed: $entry"
+                    fmt::suc "Successfully installed: $entry"
                 else
                     errored_entries+=(${entry})
                 fi
@@ -219,7 +223,7 @@ if $SETUP_PACKAGES ; then
 
     for arg in "$@" ; do
         if [[ "$arg" == "install/"* ]]; then
-            msg "Ignoring install/ pfix: $arg"
+            fmt::msg "Ignoring install/ pfix: $arg"
             arg=${arg#"install/"}
         fi
         if [ -f "$arg" ]; then
@@ -229,7 +233,7 @@ if $SETUP_PACKAGES ; then
         fi
     done
 
-    suc "Installations finished."
+    fmt::suc "Installations finished."
 fi
 
 
@@ -247,16 +251,16 @@ if $SETUP_DOTFILES ; then
         entry_path="$SETUP_HOME_DIR/$entry"
         if [[ -f $entry_path && ! -h $entry_path ]]; then
             mkdir -p $backup_dir
-            msg "Forcing overwrite of: $entry_path ; backup at $backup_dir"
+            fmt::msg "Forcing overwrite of: $entry_path ; backup at $backup_dir"
             mv "$entry_path" "$backup_dir"
         fi
     done
 
     cd dotfiles
     if stow --no-folding -v . -t "$SETUP_HOME_DIR" ; then 
-        suc "Dotfiles linked."
+        fmt::suc "Dotfiles linked."
     else
-        err "Failed linking dotfiles! Backup is kept at: $backup_dir"
+        fmt::err "Failed linking dotfiles! Backup is kept at: $backup_dir"
     fi
     cd "$DOTFILES_ROOT_DIR"
     
@@ -272,10 +276,10 @@ if $SETUP_PATCHES ; then
         if [ -f "$patches_script" ]; then
             source ./"$patches_script"
         else
-            err "$patches_dir/$patches_script script is not present."
+            fmt::err "$patches_dir/$patches_script script is not present."
         fi
     else
-        err "$patches_dir/ directory is not present."
+        fmt::err "$patches_dir/ directory is not present."
     fi
     unset patches_dir
     unset patches_script
@@ -290,10 +294,10 @@ if $SETUP_SERVICES ; then
         if [ -f "$services_script" ]; then
             source ./"$services_script"
         else
-            err "$services_dir/$services_script script is not present."
+            fmt::err "$services_dir/$services_script script is not present."
         fi
     else
-        err "$services_dir/ directory is not present."
+        fmt::err "$services_dir/ directory is not present."
     fi
     unset services_dir
     unset services_script
@@ -304,12 +308,12 @@ if $SETUP_PACKAGES ; then
     process_list "${packages_requiring_linked_dotfiles[@]}"
 
     for errored_entry in "${errored_entries[@]}"; do
-        err "Failed to install: $errored_entry"
+        fmt::err "Failed to install: $errored_entry"
     done
 fi
 
 unset SETUP_USER
 unset SETUP_HOME_DIR
 
-suc "Done! Have a nice day."
+fmt::suc "Done! Have a nice day."
 
