[shlib] update to v2

diff --git a/install/yay b/install/yay
--- a/install/yay
+++ b/install/yay
@@ -7,7 +7,7 @@ if ! inst_silent yay ; then
     sudo mkdir -p $yaydir
     sudo chown "$SETUP_USER":"$SETUP_USER" $yaydir
     git clone https://aur.archlinux.org/yay-bin.git $yaydir
-    pushd $yaydir || (std::err "failed to create installation directory for yay: $yaydir" && return)
+    pushd $yaydir || (log_err "failed to create installation directory for yay: $yaydir" && return)
     makepkg -si --noconfirm --needed
     popd
 fi
